### ISSUE TITLE
[Markup] Value Key

### ISSUE THREAD

**Issue by karai17** [excessive/DOMinatrix#15]
Should there be a value key, or should value (and sometimes children) simply be the sequential second key? Or perhaps both, with value overriding a sequential value?

``` lua
-- value key
{ "text", value="Some text", id="important_textbox", class={"class1", "class2"},
    { "text", value="Some child" },
}

-- sequential key
{ "text", "Some text", id="important_textbox", class={"class1", "class2"},
    { "text", "Some child" },
}

-- priority key
{ "text", "Some text", value="This takes priority!", id="important_textbox", class={"class1", "class2"},
    { "text", "Some child" },
}
```

**Comment by adrix89** [comment]
If you can do whatever.value to set it that would make more sense then whatever[2]
If you are setting the value with a function then there is no point for an extra value field.
Priority override makes sense technically since the important one is the value as that would be changed but maybe it doesn't make sense in terms of clarity.

**Comment by karai17** [comment]
Well, it wouldn't be whatever[2], this is strictly for markup. See the
above examples.

**Comment by karai17** [comment]
I've decided to go with the priority bit. You can use either element[2] or element.value to assign a value where element.value takes priority in the case that both are given.
