### ISSUE TITLE
Custom draw functions

### ISSUE THREAD

**Issue by karai17** [excessive/DOMinatrix#22]
need to figure this one out.

**Comment by adrix89** [comment]
If it is overridden treat it as separate from the batches.
The default function handles adding to batches and stuff.
You would need a separate draw function from the batches and need to handle the draw order so that the batches sandwich the custom and animated stuff.

Alternatively don't have custom draw functions OR don't use spritebatch.
You might be able to so some tricks with canvas and masking in which case you draw the spritebatch first and do the tricks after but i can't help you there since I have no idea how it would work.
